In [321]:
import pandas as pd

In [322]:
df = pd.read_excel(r"C:\Users\benmc\OneDrive\Desktop\Sales Analytics\data\raw_sales_data.xls")

In [323]:
df.duplicated().sum()

np.int64(0)

In [324]:
df.describe()

,Row ID,Order Date,Ship Date,Sales,Quantity,Discount,Profit
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2025-04-29 11:48:25.002943,2025-05-03 10:52:45.626839,228.225854,3.791838,0.155385,28.673417
min,1.000000,2023-01-03 00:00:00,2023-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,2024-05-14 00:00:00,2024-05-19 00:00:00,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,2025-06-25 00:00:00,2025-06-28 00:00:00,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,2026-05-14 00:00:00,2026-05-18 00:00:00,209.500000,5.000000,0.200000,29.297925
max,10194.000000,2026-12-30 00:00:00,2027-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [325]:
df["Country/Region"].value_counts()

Country/Region
United States    9994
Canada            200
Name: count, dtype: int64

In [326]:
df.nunique()

Row ID            10194
Order ID           5111
Order Date         1242
Ship Date          1338
Ship Mode             4
Customer ID         804
Customer Name       800
Segment               3
Country/Region        2
City                542
State/Province       59
Postal Code         654
Region                4
Product ID         1862
Category              3
Sub-Category         17
Product Name       1849
Sales              6161
Quantity             14
Discount             12
Profit             7597
dtype: int64

In [327]:
df["Year"] = df["Order Date"].dt.year

In [328]:
df["Month Number"] = df["Order Date"].dt.month

In [329]:
df["Month"] = df["Order Date"].dt.strftime("%B")

In [330]:
df["Quarter"] = df["Order Date"].dt.quarter

In [331]:
df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [332]:
df["Profit Margin"] = (df["Profit"] / df["Sales"]) * 100

In [333]:
df["Order Month"] = df["Order Date"].dt.to_period("M").astype(str)

In [334]:
df.to_csv(
    r"C:\Users\benmc\OneDrive\Desktop\Sales Analytics\data\superstore_cleaned.csv",
    index=False
)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\benmc\\OneDrive\\Desktop\\Sales Analytics\\data\\superstore_cleaned.csv'

In [ ]:
# Total Revenue
total_sales = df["Sales"].sum()

# Total Profit
total_profit = df["Profit"].sum()

# Average Shipping Time
avg_shipping = df["Shipping Days"].mean()

print(f"Total Revenue: ${total_sales:,.2f}")
print(f"Total Profit: ${total_profit:,.2f}")
print(f"Average Shipping Time: {avg_shipping:.2f} days")

Total Revenue: $2,326,534.35
Total Profit: $292,296.81
Average Shipping Time: 3.96 days

In [ ]:
df.groupby("Category")["Profit"].sum().sort_values(ascending=False)

Category
Technology         146543.3756
Office Supplies    126023.4434
Furniture           19729.9956
Name: Profit, dtype: float64

In [ ]:
df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

Category
Technology         839893.2790
Furniture          754747.7613
Office Supplies    731893.3140
Name: Sales, dtype: float64

In [ ]:
df[df["Category"]=="Furniture"].groupby(
    "Sub-Category"
)[["Sales","Profit"]].sum().sort_values(
    by="Profit"
)

                    Sales      Profit
Sub-Category
Tables        208020.1820 -17753.2061
Bookcases     115361.2043  -3632.0736
Furnishings    95598.1260  13891.7430
Chairs        335768.2490  27223.5323

In [ ]:
df[df["Sub-Category"]=="Tables"].groupby(
    "Discount"
)[["Sales","Profit"]].sum()

              Sales      Profit
Discount
0.00      71706.230  13334.9247
0.20      45636.582   -298.3980
0.30      25902.980  -3493.8376
0.40      45614.406 -16187.3968
0.45       5484.974  -2493.1111
0.50      13675.010  -8615.3873

In [ ]:
df[df["Sub-Category"]=="Tables"].groupby(
    "Region"
)[["Sales","Profit"]].sum()

             Sales      Profit
Region
Central  39154.971  -3559.6504
East     39926.147 -11086.1471
South    43916.192  -4623.0579
West     85022.872   1515.6493

In [ ]:
df[
    (df["Sub-Category"]=="Tables") &
    (df["Region"]=="East")
].groupby(
    "Discount"
)[["Sales","Profit"]].sum()

              Sales     Profit
Discount
0.0          65.510    30.7430
0.3       10142.319 -1277.1610
0.4       29718.318 -9839.7291

In [ ]:
df[df["Sub-Category"]=="Tables"].groupby(
    "Product Name"
)[["Sales","Profit"]].sum().sort_values(
    by="Profit"
)

                                                         Sales     Profit
Product Name
Chromcraft Bull-Nose Wood Oval Conference Table...   9917.6400 -2876.1156
Bush Advantage Collection Racetrack Conference ...   9544.7250 -1934.3976
Balt Solid Wood Round Tables                         6518.7540 -1201.0581
BoxOffice By Design Rectangular and Half-Moon M...   1706.2500 -1148.4375
Riverside Furniture Oval Coffee Table, Oval End...   4446.1750 -1147.4000
Bretford “Just In Time” Height-Adjustable Multi...   5634.9000  -964.1940
Bevis Oval Conference Table, Walnut                  6942.0680  -856.0144
BPI Conference Tables                                2241.8675  -795.9725
Hon 94000 Series Round Tables                        7404.5000  -681.2140
Chromcraft Bull-Nose Wood 48" x 96" Rectangular...   4297.6440  -611.5878
Hon Racetrack Conference Tables                      3963.9010  -598.5228
Bevis Rectangular Conference Tables                  1007.2620  -586.8396
Bretford CR4500 Series Slim Rectangular Table        7242.7680  -532.7613
Bevis Round Conference Table Top, X-Base             2671.4210  -519.9410
KI Conference Tables                                 2140.8780  -479.2164
Bevis Traditional Conference Table Top, Plinth ...   2033.4960  -456.7032
Chromcraft Rectangular Conference Tables             4952.6730  -450.2430
Bevis Boat-Shaped Conference Table                   2542.4670  -445.5870
Riverside Furniture Stanwyck Manor Table Series       917.9200  -415.9325
Chromcraft 48" x 96" Racetrack Double Pedestal ...   5098.1760  -404.0064
Hon 2111 Invitation Series Corner Table              3140.5500  -401.9904
Iceberg OfficeWorks 42" Round Tables                 3457.4420  -392.5480
Balt Split Level Computer Training Table             1256.6850  -386.6210
Bretford Rectangular Conference Table Tops          13565.5715  -359.3541
Lesro Round Back Collection Coffee Table, End T...   2847.7800  -328.5900
Hon Rectangular Conference Tables                    3481.5150  -295.8150
Hon 5100 Series Wood Tables                          5965.0900  -238.6036
Balt Solid Wood Rectangular Table                     828.0965  -216.2545
KI Adjustable-Height Table                           4820.9510  -215.4402
Laminate Occasional Tables                           2096.1680  -206.5342
Bevis Round Bullnose 29" High Table Top              4544.9250  -192.1854
Chromcraft Round Conference Tables                   8209.0590  -189.9761
Hon 30" x 60" Table with Locking Drawer              1296.0280  -177.3512
Bevis 44 x 96 Conference Tables                      3253.2200  -164.7200
Hon 61000 Series Interactive Training Tables          653.1210  -148.3962
Bush Andora Conference Table, Maple/Graphite Gr...   1436.2320  -143.6232
Hon 2111 Invitation Series Straight Table            2040.0540  -115.3074
Barricks 18" x 48" Non-Folding Utility Table wi...   1088.6400  -104.8320
Office Impressions End Table, 20-1/2"H x 24"W x...   5801.8160   -66.8272
Bevis Round Conference Room Tables and Bases          519.9410   -39.4438
Anderson Hickey Conga Table Tops & Accessories         51.7820   -17.5145
Lesro Sheffield Collection Coffee Table, End Ta...   2298.1140   -12.1329
Barricks Non-Folding Utility Table with Steel L...    136.4640    15.3522
Safco Drafting Table                                  638.8200    34.0704
SAFCO PlanMaster Boards, 60w x 37-1/2d, White M...   2979.0040    54.7164
Hon 4060 Series Tables                               1231.5600    96.2856
Chromcraft Bull-Nose Wood Round Conference Tabl...   3354.8900   100.2110
Bevis Round Conference Table Top & Single Colum...   2297.5380   100.9746
Bush Advantage Collection Round Conference Table     3401.6000   210.4740
Bush Cubix Conference Tables, Fully Assembled        3603.2880   311.8230
Global Adaptabilities Conference Tables              3540.3480   354.0348
Hon Practical Foundations 30 x 60 Training Tabl...   4334.8275   430.0695
Bevis 36 x 72 Conference Tables                      4332.2520   448.1640
Bretford CR8500 Series Meeting Room Furniture        6776.5620   461.1270
Hon Non-Folding Utility Tables                       3775.6470   541.6540
SAFCO PlanMaster Heigh-Adjustable Drafting Tabl...   3739.1150   608.0430

In [ ]:
df.groupby("Discount")[["Sales","Profit"]].sum()

                 Sales       Profit
Discount
0.00      1.105324e+06  326718.5872
0.10      5.495250e+04    9099.9700
0.15      2.755852e+04    1418.9915
0.20      7.739394e+05   91079.9517
0.30      1.044741e+05  -10513.4456
0.32      1.449346e+04   -2391.1377
0.40      1.164978e+05  -23086.3742
0.45      5.484974e+03   -2493.1111
0.50      5.891854e+04  -20506.4281
0.60      7.105940e+03   -6164.3472
0.70      4.080527e+04  -40300.5727
0.80      1.698015e+04  -30565.2692

In [ ]:
df.groupby("Discount")["Profit Margin"].mean()

Discount
0.00     34.129259
0.10     15.462963
0.15      3.416290
0.20     17.656835
0.30    -11.571430
0.32    -17.429194
0.40    -22.318841
0.45    -45.454545
0.50    -54.909091
0.60    -67.382349
0.70    -79.646295
0.80   -182.425371
Name: Profit Margin, dtype: float64

In [ ]:
def discount_band(discount):
    if discount == 0:
        return "No Discount"
    elif discount <= 0.2:
        return "Low Discount"
    elif discount <= 0.4:
        return "Medium Discount"
    else:
        return "High Discount"

df["Discount Band"] = df["Discount"].apply(discount_band)

In [ ]:
df.groupby("Discount Band")[["Sales","Profit"]].sum()

                        Sales       Profit
Discount Band
High Discount    1.292949e+05 -100029.7283
Low Discount     8.564504e+05  101598.9132
Medium Discount  2.354653e+05  -35990.9575
No Discount      1.105324e+06  326718.5872

In [ ]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country/Region',
 'City',
 'State/Province',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Year',
 'Month Number',
 'Month',
 'Quarter',
 'Shipping Days',
 'Profit Margin',
 'Order Month',
 'Discount Band']

In [ ]:
len(df.columns)

29